export const SYMBOLS = [
  { char: '☺', name: 'rosto sorridente' },
  { char: 'ツ', name: 'rosto sorridente' },
  { char: '♥', name: 'coração' },
  { char: '✰', name: 'estrela' },
  { char: '♡', name: 'coração vazado' },
  { char: '♪', name: 'nota musical' },
  { char: '☪', name: 'lua e estrela' },
  { char: '𓅪', name: 'pássaro' },
  { char: '👁', name: 'olho' },
  { char: '►', name: 'triângulo' },
  { char: '•', name: 'ponto' },
  { char: '©', name: 'copyright' },
  { char: '■', name: 'quadrado' },
  { char: '√', name: 'raiz quadrada' },
  { char: '☀', name: 'sol' },
  { char: '𝛑', name: 'pi' },
  { char: '➳', name: 'flecha' },
  { char: '⚑', name: 'marcador' },
  { char: 'ᵔᴥᵔ', name: 'urso' },
  { char: '☠', name: 'caveira' },
  { char: '†', name: 'cruz' },
  { char: '🗓', name: 'calendário' },
  { char: '☮', name: 'paz' },
  { char: '𓆏', name: 'ra' },
  { char: '❀', name: 'planta' },
  { char: '✿', name: 'flor' }
]